version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres123
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_SERVER}
      POSTGRES_PORT: ${POSTGRES_PORT}

  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
      bash -c "
      sleep 10 &&
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"

